- job-template:
    name: 'ops-config-container-check-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 10
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-container'
            platform: '{platform}'
        - yaml-lint:
            file:
              - 'src/ops-config-container/*.yaml'

- job-template:
    name: 'ops-config-container-gate-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-container'
            platform: '{platform}'
        - yaml-lint:
            file:
              - 'src/ops-config-container/*.yaml'

- job-group:
    name: 'ops-config-container-jobs'
    jobs:
      - 'ops-config-container-check-{platform}'
      - 'ops-config-container-gate-{platform}'
